"""Add manager feedback model

Revision ID: 94fcd476205d
Revises: ed3c246b0e5a
Create Date: 2026-05-19 04:21:14.858253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.base import GUID


# revision identifiers, used by Alembic.
revision: str = '94fcd476205d'
down_revision: Union[str, Sequence[str], None] = 'ed3c246b0e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_feedback',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('performance_rating', sa.Enum('exceeds_expectations', 'meets_expectations', 'needs_improvement', name='performancerating'), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=False),
    sa.Column('development_areas', sa.Text(), nullable=False),
    sa.Column('discussion_summary', sa.Text(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_feedback_created_at'), 'manager_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_manager_feedback_employee_id'), 'manager_feedback', ['employee_id'], unique=False)
    op.create_index(op.f('ix_manager_feedback_id'), 'manager_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_manager_feedback_quarter'), 'manager_feedback', ['quarter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manager_feedback_quarter'), table_name='manager_feedback')
    op.drop_index(op.f('ix_manager_feedback_id'), table_name='manager_feedback')
    op.drop_index(op.f('ix_manager_feedback_employee_id'), table_name='manager_feedback')
    op.drop_index(op.f('ix_manager_feedback_created_at'), table_name='manager_feedback')
    op.drop_table('manager_feedback')
    # ### end Alembic commands ###
